#!/bin/sh
git clone https://github.com/pyenv/pyenv.git ~/.pyenv && \
export PYENV_ROOT="$HOME/.pyenv" && \
export PATH="$PYENV_ROOT/bin:$PATH"
# ~Check clone worked OK
if [ $? -ne 0 ]; then
  exit 1
fi

# Set up pyenv and install the version of Python required
eval "$(pyenv init -)" 
pyenv install ${PYTHON_VERSION}
if [ $? -ne 0 ]; then
  exit 1
fi

# Load the Python env into the shell
eval "$(pyenv init --path)" 
pyenv shell ${PYTHON_VERSION}
if [ $? -ne 0 ]; then
  exit 1
fi

# Install any additional modules
if [ $# != 0 ]; then
  packages=$@
  if [ ! ${packages} == "." ]; then
    pip install $@
    if [ $? -ne 0 ]; then
      exit 1
    fi
  fi
fi

# Prepare the build directories
cd /
mkdir -p build/bin
mkdir -p build/lib
cp -r $PYENV_ROOT build/pyenv
cd build/bin
ln -s ../pyenv/versions/${PYTHON_VERSION}/bin/python python
ln -s ../pyenv/versions/${PYTHON_VERSION}/bin/pip pip

# Validate packages have been installed
if [ $# != 0 ]; then
  packages=$@
  if [ ! ${packages} == "." ]; then
    for package in "${packages}"; do
      pip show ${package} || (>&2 echo "Failed to find package"; exit 1)
      if [ $? -ne 0 ]; then
        exit 1
      fi
    done
  fi
fi