name: Check tagged commit

on:
  pull_request:

jobs:
  check_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check tag
        uses: actions/github-script@v5
        with:
          script: |
            const tag = context.payload.pull_request.head.ref
            # Check tag exists
            if (!tag) {
              core.setFailed('Tag does not exist')
            }
            if (!tag.startsWith('v')) {
              core.setFailed(`Tag ${tag} does not start with 'v'`)
            }
