name: Add assets to release

on:
  release:
    types: [published]
    tags:
      - "v*.*"

jobs:
  setup_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        # Read the contents of the matrix.json file into the matrix variable
        run: |
          matrix=$(jq -Mc . matrix.json)
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
  pull_artifacts:
    needs: setup_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ${{ fromJSON(needs.setup_matrix.outputs.matrix).platform }}
        package_group: ${{ fromJSON(needs.setup_matrix.outputs.matrix).python_package_groups }}
    steps:
      - name: Download asset artifact
        if: ${{ !env.ACT }} # Skip step if running locally
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.PYTHON_VERSION }}-${{ env.PLATFORM_NAME }}-${{ env.ASSET_VERSION }}
          path: dist/
  release:
    name: Release assets
    needs: [setup_matrix, pull_artifacts]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Add files to release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          files: dist/*.tar.gz
          generate_release_notes: true
